---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wordpress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: shawn@diggingin.pw # Replace with your email address
    privateKeySecretRef:
      name: letsencrypt-wordpress-stack
    solvers:
      - http01:
          ingress:
            class: nginx #CHANGE
