apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  namespace: media-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    gethomepage.dev/description: qBittorrent
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: https://www.qbittorrent.org/favicon.ico
    gethomepage.dev/name: qBittorrent
    gethomepage.dev/pod-selector: ""
    
spec:
  rules:
    - host: qbittorrent.rke
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent-webui
                port:
                  number: 8112
