apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jar-explorer-config-pvc
  namespace: minecraft-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class