apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-plugins
  namespace: minecraft-stack
data:
  mods.txt: |
    https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
    https://download.luckperms.net/1573/bukkit/loader/LuckPerms-Bukkit-5.4.156.jar
    https://github.com/fuzziejaxer/LuckPermsGUI/releases/download/1.16.5/luckpermsgui-1.6.1-SNAPSHOT-all.jar
    https://github.com/ThizThizzyDizzy/tree-feller/releases/download/v1.25.1/TreeFeller-1.25.1.jar
    https://dev.bukkit.org/projects/worldguard/files/6201343/download
    https://dev.bukkit.org/projects/worldedit/files/6122276/download
    https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.7/bluemap-5.7-spigot.jar
    https://dev.bukkit.org/projects/multiverse-core/files/5901717/download
    https://dev.bukkit.org/projects/multiverse-portals/files/4721154/download
    https://dev.bukkit.org/projects/multiverse-inventories/files/4721185/download
    https://dev.bukkit.org/projects/valhallammo/files/6214587/download
    https://dev.bukkit.org/projects/grief-prevention/files/5471866/download
    https://dev.bukkit.org/projects/blockprot/files/5991184/download
    https://dev.bukkit.org/projects/cookieminion/files/6186178/download
    https://dev.bukkit.org/projects/vault/files/3007470/download
    https://dev.bukkit.org/projects/automessage/files/911506/download