apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: media-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre
          image: linuxserver/calibre:latest
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York" # Replace with your timezone
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: calibre-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: calibre-samba-pvc
