apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: minecraft-stack
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        command:
          - "cloudflared"
          - "tunnel"
          - "--no-autoupdate"
          - "run"
          - "--token"
          - "$(TUNNEL_TOKEN)"  # Direct environment variable substitution
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-tunnel-secret
              key: TUNNEL_TOKEN
