apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-config-pvc
  namespace: monitoring-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn # Explicitly set Longhorn as the storage class