apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server
          env:
            - name: PLUGINS
              value: |
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/BlueMap-Essentials-1.1.3.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/CoreProtect-22.0.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/Craft-GPT-Plugin-1.20.1.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/CustomRecipeAPI-1.6.0.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/EssentialsX-2.20.1.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/LuckPerms-Bukkit-5.4.40.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/TreeFeller-1.22.1.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/luckpermsgui-1.7.1-all.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/worldedit-bukkit-7.2.15.jar
                https://github.com/jtmb/branconet-homelab/blob/1bc4ba86f3546b08941c6539da928a6c46c61016/docker-compose/swarm/game-servers/minecraft/plugins/worldguard-bukkit-7.0.9-dist.jar
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York" # Replace with your timezone
            - name: MEMORY
              value: "2G"
            - name: MAX_MEMORY
              value: "4G"
            - name: INIT_MEMORY
              value: "2G"
            - name: MOTD
              value: "Defeating a sandwich only makes it tastier."
            - name: ENABLE_RCON
              value: "TRUE"
            - name: EXEC_DIRECTLY
              value: "TRUE"
            - name: CPUS
              value: "2"
            - name: EULA
              value: "TRUE"
            - name: TUNE_VIRTUALIZED
              value: "TRUE"
            - name: TUNE_NURSERY_SIZES
              value: "TRUE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minecraft-server-rcon-secret
                  key: password
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /data
            - name: configmap
              mountPath: /data/ops.json
              subPath: ops.json
            - name: configmap
              mountPath: /data/Essentials/config.yml
              subPath: config.yml
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: minecraft-server-config-pvc
        - name: configmap
          configMap:
            name: minecraft-server
