apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database-pvc
  namespace: rom-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config-pvc
  namespace: rom-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: roms-samba-pv
spec:
  capacity:
    storage: 1Gi # Updated to reflect a larger capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: radarr-samba-share
    volumeAttributes:
      source: "//10.10.68.155/smb_drive/nintendo" # Explicitly define the source field
      options: "uid=0,gid=0,forceuid,forcegid,file_mode=0755"
    nodeStageSecretRef:
      name: samba-secret
      namespace: rom-stack