apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: minecraft-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - minecraft-server
              topologyKey: "kubernetes.io/hostname"  # Ensure this is set correctly
      containers:
        - name: filebrowser
          image: hurlenko/filebrowser
          env:
            - name: FB_BASEURL
              value: /filebrowser
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data_dir
              mountPath: /data
            - name: config
              mountPath: /config
            - name: mc-data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: filebrowser-config-pvc
        - name: data_dir
          persistentVolumeClaim:
            claimName: filebrowser-database-pvc
        - name: mc-data
          persistentVolumeClaim:
            claimName: minecraft-server-config-pvc
