apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-config-pvc
  namespace: minecraft-stack
spec:
  accessModes:
    - ReadWriteMany #allows pvc to be mounted by multiple pods
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class