apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-config-pvc
  namespace: minecraft-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class