apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sweeparr-data-pvc
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
