apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett-ingress
  namespace: media-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    gethomepage.dev/description: Jackett is a torrent proxy
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: http://jackett.rke/jacket_medium.png
    gethomepage.dev/name: Jackett
    gethomepage.dev/pod-selector: ""
spec:
  rules:
    - host: jackett.rke # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jackett-service
                port:
                  number: 9117
