apiVersion: apps/v1
kind: Deployment
metadata:
  name: fringe-salon-redis
  namespace: wordpress-stack
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fringe-salon-redis
  template:
    metadata:
      labels:
        app: fringe-salon-redis
    spec:
      containers:
        - name: fringe-salon-redis
          image: redis:alpine
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York" # Replace with your timezone
          ports:
            - containerPort: 6379
              protocol: TCP