apiVersion: v1
kind: Service
metadata:
  name: fringe-salon-redis-service
  namespace: wordpress-stack
spec:
  selector:
    app: fringe-salon-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP