apiVersion: v1
kind: Service
metadata:
  name: readarr-service
  namespace: media-stack
spec:
  selector:
    app: readarr
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
  type: ClusterIP
