apiVersion: v1
kind: Service
metadata:
  name: snipeit-postgres-service
  namespace: snipeit
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: snipeit-postgres
  type: ClusterIP
