apiVersion: apps/v1
kind: Deployment
metadata:
  name: fringe-salon-mysql
  namespace: wordpress-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fringe-salon-mysql
  template:
    metadata:
      labels:
        app: fringe-salon-mysql
    spec:
      containers:
        - name: fringe-salon-mysql
          image: mysql:5.7
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York" # Replace with your timezone
            - name: MYSQL_USER
              value: db_user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: password
            - name: MYSQL_DATABASE
              value : wp_db
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: '1'
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /var/lib/mysql
              subPath: mysql
          readinessProbe:
            exec:
              command:
              - mysqladmin
              - ping
              - "-h"
              - "localhost"
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
              - "-h"
              - "localhost"
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: fringe-salon-mysql-config-pvc