apiVersion: v1
kind: Service
metadata:
  name: fringe-salon-mysql-service
  namespace: wordpress-stack
spec:
  selector:
    app: fringe-salon-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP