apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-service
  namespace: homepage-stack
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  # settings.yaml: ""
  settings.yaml: |
    title: Shak Net 2.0
    description: The second revision to the greatness
    background:
      image: https://i.imgur.com/lMhP5fR.jpeg
      opacity: 40
      brightness: 50
    theme: dark
    color: green
    layout:
      Media:
        style: row
        columns: 3
      Sys Admin:
        style: row
        columns: 3
    headerStyle: boxedWidgets
    
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  
  # bookmarks.yaml: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/shakiata/
    - Managment:
        - ESXI:
            - abbr: ESXI
              href: http://10.10.68.7/
              description: Don't Touch
        - PFSENSE:
            - abbr: PF
              href: http://10.10.68.1
              description: Firewall
        - PiHole:
            - abbr: PI
              href: http://pi.box/admin/login.php

  services.yaml: ""
  # services.yaml: |

  #   # - My Second Group:
  #   #     - My Second Service:
  #   #         href: http://localhost/
  #   #         description: Homepage is the best

  #   # - My Third Group:
  #   #     - My Third Service:
  #   #         href: http://localhost/
  #   #         description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - nzbget
        type: nzbget
        url: http://nzbget.rke
        username: homepage
        password: test1
  docker.yaml: ""