apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hompage-config-pvc
  namespace: homepage-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn # Explicitly set Longhorn as the storage class

