apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbgett-ingress
  namespace: media-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # gethompage.dev/decscription: NZBGett
    # gethomepage.dev/enabled: "true"
    # gethomepage.dev/group: Media
    # gethomepage.dev/icon: http://nzbgett.rke/img/icons.png
spec:
  rules:
    - host: nzbgett.rke # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nzbgett-service
                port:
                  number: 6789
